import{S as L,a as v,i as c}from"./assets/vendor-xJi9366P.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function l(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=l(e);fetch(e.href,o)}})();const t={gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader-wrapper"),loadMore:document.querySelector(".load-more")},f=new L(".gallery a",{captionsData:"alt"});function p(r){return r.map(({largeImageURL:a,webformatURL:l,tags:s,likes:e,views:o,comments:n,downloads:b})=>`<li class="gallery-item">
            <a href="${a}">
              <img class="gallery-img" src="${l}" alt="${s}" loading="lazy"/>
            </a>
            <div class="gallery-wrapper">
              <p class="wrapper-list"><b>likes:</b> ${e}</p>
              <p class="wrapper-list"><b>views:</b> ${o}</p>
              <p class="wrapper-list"><b>comments:</b> ${n}</p>
              <p class="wrapper-list"><b>downloads:</b> ${b}</p>
            </div>
          </li>`).join("")}function w(r){t.gallery&&(t.gallery.innerHTML=p(r),f.refresh())}function M(r){t.gallery&&(t.gallery.insertAdjacentHTML("beforeend",p(r)),f.refresh())}function P(){t.gallery&&(t.gallery.innerHTML="")}function y(){t.loader&&t.loader.classList.add("visible")}function S(){t.loader&&t.loader.classList.remove("visible")}function g(){t.loadMore&&t.loadMore.classList.add("visible")}function u(){t.loadMore&&t.loadMore.classList.remove("visible")}const q="https://pixabay.com/api/",$="55068901-115bb3486aee025ccc29fb7ad";async function m(r,a){return(await v.get(q,{params:{key:$,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:a}})).data}const h={form:document.querySelector(".form"),loadMore:document.querySelector(".load-more")};let d="",i=1;h.form.addEventListener("submit",async r=>{var l;r.preventDefault();const a=r.target.elements["search-text"].value.trim();if(a===""){c.error({message:"Please enter a search query"});return}d=a,i=1,P(),y(),u();try{const s=await m(d,i),e=Math.ceil(s.totalHits/15);if(i<e?g():u(),!((l=s==null?void 0:s.hits)!=null&&l.length)){c.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}w(s.hits),i+=1,r.target.reset()}catch{c.error({message:"Something went wrong. Please try again later."})}finally{S()}});h.loadMore.addEventListener("click",async r=>{r.preventDefault(),y(),u();const a=await m(d,i);M(a.hits);const l=Math.ceil(a.totalHits/15);i<l?g():u(),c.info({message:"We're sorry, but you've reached the end of search results"}),i+=1});
//# sourceMappingURL=index.js.map
