import{S as p,a as f,i as n}from"./assets/vendor-Bm2N4jGG.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const l={gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader")},m=new p(".gallery a",{captionsData:"alt"});function d(o){const t=o.map(({largeImageURL:s,webformatURL:a,tags:e,likes:r,views:i,comments:c,downloads:u})=>`<li class="gallery-item">
            <a href="${s}">
              <img class="gallery-img" src="${a}" alt="${e}" loading="lazy"/>
            </a>
            <div class="gallery-wrapper">
              <p class="wrapper-list"><b>likes</b>${r}</p>
              <p class="wrapper-list"><b>views</b>${i}</p>
              <p class="wrapper-list"><b>comments</b>${c}</p>
              <p class="wrapper-list"><b>downloads</b>${u}</p>
            </div>
          </li>`).join("");l.gallery.innerHTML=t,m.refresh()}function g(){l.gallery.innerHTML=""}function y(){l.loader.classList.add("visible")}function h(){l.loader.classList.remove("visible")}const b="https://pixabay.com/api/";function L(o){return f.get(b,{params:{key:"55068901-115bb3486aee025ccc29fb7ad",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(t=>t.data)}const w={form:document.querySelector(".form")};w.form.addEventListener("submit",o=>{o.preventDefault();const t=o.target.elements["search-text"].value.trim();if(t===""){n.error({message:"Please enter a search query"});return}y(),g(),L(t).then(s=>{var a;if(!((a=s==null?void 0:s.hits)!=null&&a.length)){n.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}o.target.reset(),d(s.hits)}).catch(s=>{n.error({message:"Something went wrong. Please try again later."})}).finally(()=>{h()})});
//# sourceMappingURL=index.js.map
