import{S as v,a as M,i}from"./assets/vendor-xJi9366P.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const a={gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader-wrapper"),loadMore:document.querySelector(".load-more")},g=new v(".gallery a",{captionsData:"alt"});function y(t){return t.map(({largeImageURL:s,webformatURL:o,tags:n,likes:e,views:r,comments:c,downloads:w})=>`<li class="gallery-item">
            <a href="${s}">
              <img class="gallery-img" src="${o}" alt="${n}" loading="lazy"/>
            </a>
            <div class="gallery-wrapper">
              <p class="wrapper-list"><b>likes:</b> ${e}</p>
              <p class="wrapper-list"><b>views:</b> ${r}</p>
              <p class="wrapper-list"><b>comments:</b> ${c}</p>
              <p class="wrapper-list"><b>downloads:</b> ${w}</p>
            </div>
          </li>`).join("")}function P(t){a.gallery&&(a.gallery.innerHTML=y(t),g.refresh())}function S(t){a.gallery&&(a.gallery.insertAdjacentHTML("beforeend",y(t)),g.refresh())}function q(){a.gallery&&(a.gallery.innerHTML="")}function p(){a.loader&&a.loader.classList.add("visible")}function m(){a.loader&&a.loader.classList.remove("visible")}function h(){a.loadMore&&a.loadMore.classList.add("visible")}function u(){a.loadMore&&a.loadMore.classList.remove("visible")}const $="https://pixabay.com/api/",E="55068901-115bb3486aee025ccc29fb7ad";async function b(t,s){return(await M.get($,{params:{key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:s}})).data}const d={form:document.querySelector(".form"),loadMore:document.querySelector(".load-more")};let f="",l=1;const L=15;d.form.addEventListener("submit",async t=>{var o;t.preventDefault();const s=t.target.elements["search-text"].value.trim();if(s===""){i.error({message:"Please enter a search query"});return}f=s,l=1,q(),p(),u();try{const n=await b(f,l);if(!((o=n==null?void 0:n.hits)!=null&&o.length)){i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}P(n.hits);const e=Math.ceil(n.totalHits/L);l===e?(u(),i.info({message:"We're sorry, but you've reached the end of search results"})):h(),l+=1,t.target.reset()}catch{i.error({message:"Something went wrong. Please try again later."})}finally{m()}});d.loadMore&&d.loadMore.addEventListener("click",async t=>{var s;t.preventDefault(),p(),u();try{const o=await b(f,l);if(!((s=o==null?void 0:o.hits)!=null&&s.length)){u(),i.info({message:"We're sorry, but you've reached the end of search results"});return}S(o.hits);const n=Math.ceil(o.totalHits/L);if(l+=1,l>n){u(),i.info({message:"We're sorry, but you've reached the end of search results"});return}else h();const e=document.querySelector(".gallery-item");if(!e)return;const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}catch{i.error({message:"Something went wrong. Please try again later."})}finally{m()}});
//# sourceMappingURL=index.js.map
